version: '3.8'
services:
  elasticsearch-v2:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.8
    container_name: elasticsearch-marketplace-v2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
  # NOVO: Container Semeador de Dados
  elasticsearch-seeder:
    image: curlimages/curl:8.4.0 # Uma imagem super leve que só serve para rodar requisições web
    container_name: elasticsearch-seeder
    depends_on:
      - elasticsearch-v2 # Garante que só vai ligar depois do banco
    volumes:
      - ./init-data.sh:/init-data.sh # Joga o script para dentro do container
    command: ["/bin/sh", "/init-data.sh"] # Manda o container rodar o script