spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**

server:
  port: 9999

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0