spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**
            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/products/**
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true